# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCity
  pod 'R.swift'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'RealmSwift'
  pod 'RxRealm'

  target 'MyCityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCityUITests' do
    # Pods for testing
  end

end
